- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no
  vars:
    homebrew_packages_taps:
      - caskroom/cask
      - homebrew/php
      - homebrew/apache
      - sanemat/font

    homebrew_packages_packages:
      - { name: ansible }
      - { name: boris }
      - { name: brew-cask }
      - { name: colordiff }
      - { name: composer }
      - { name: coreutils }
      - { name: git }
      - { name: graphviz }
      - { name: htop-osx }
      - { name: httpd22 }
      - { name: hub }
      - { name: jq }
      - { name: mysql }
      - { name: nkf }
      - { name: node }
      - { name: openssl }
      - { name: php56, install_options: "homebrew-apxs,enable-intl" }
      - { name: php56-opcache }
      - { name: php56-apcu }
      - { name: php56-mcrypt }
      - { name: php56-xdebug }
      - { name: php56-xhprof }
      - { name: phpunit }
      - { name: python }
      - { name: reattach-to-user-namespace }
      - { name: ricty }
      - { name: sl }
      - { name: sqlite }
      - { name: tig }
      - { name: tmux }
      - { name: tree }
      - { name: unrar }
      - { name: wget }
      - { name: zsh }
      - { name: zsh-completions }

    homebrew_cask_packages_packages:
      - avast
      - caffeine
      - clipmenu
      - cooviewer
      - dropbox
      - eclipse-java
      - evernote
      - filezilla
      - firefox
      - flash-player
      - google-chrome
      - google-drive
      - google-japanese-ime
      - gyazo
      - heroku-toolbelt
      - java
      - karabiner
      - kobito
      - libreoffice
      - macdown
      - phpstorm
      - reaper
      - slack
      - skitch
      - skype
      - spectacle
      - sublime-text
      - vagrant
      - virtualbox
      - vlc
      - xmind
      - xtrafinder
      - xquartz

  roles:
    - hnakamur.homebrew-packages
    - hnakamur.homebrew-cask-packages

  tasks:
    - name: configure apache
      patch: src=patches/httpd.conf.patch dest=/usr/local/etc/apache2/2.2/httpd.conf basedir=.

    - name: put a sample conf file for vhosts
      template: src=templates/httpd-vhosts.conf.sample dest=/usr/local/etc/apache2/2.2/extra/httpd-vhosts.conf.sample

    - name: configure php
      patch: "src={{ item.src }} dest={{ item.dest }} basedir=."
      with_items:
        - { src: patches/php.ini.patch, dest: /usr/local/etc/php/5.6/php.ini }
        - { src: patches/ext-xdebug.ini.patch, dest: /usr/local/etc/php/5.6/conf.d/ext-xdebug.ini }

    - name: symlink xhprof into DocumentRoot
      file: "src={{ item.src }} dest={{ item.dest }} state=link"
      with_items:
        - { src: /usr/local/opt/php56-xhprof/xhprof_html, dest: /usr/local/var/www/htdocs/xhprof/xhprof_html }
        - { src: /usr/local/opt/php56-xhprof/xhprof_lib, dest: /usr/local/var/www/htdocs/xhprof/xhprof_lib }

    - name: put a snippet file into xhprof dir
      copy: src=templates/xhprof.snippet dest=/usr/local/var/www/htdocs/xhprof/xhprof.snippet
